PKG_NAME="toolchain"
PKG_VERSION=""
PKG_LICENSE="GPL"
PKG_SITE="https://libreelec.tv"
PKG_URL=""
PKG_DEPENDS_TARGET="configtools:host make:host xz:host sed:host pkg-config:host autoconf:host automake:host intltool:host libtool:host autoconf-archive:host gcc:host bison:host flex:host cmake:host xmlstarlet:host p7zip:host pigz:host ninja:host meson:host"
PKG_SECTION="virtual"
PKG_LONGDESC="Clue toolchain to compile all packages"
