PKG_NAME="linux-firmware"
PKG_VERSION=""
PKG_LICENSE="GPL"
PKG_SITE=""
PKG_URL=""
PKG_DEPENDS_TARGET="toolchain $FIRMWARE"
PKG_SECTION="virtual"
PKG_LONGDESC="linux-firmware is a meta-package to install various free firmware drivers"
