PKG_NAME="alsa"
PKG_VERSION=""
PKG_LICENSE="GPL"
PKG_SITE="http://www.alsa-project.org/"
PKG_URL=""
PKG_DEPENDS_TARGET="toolchain alsa-lib alsa-utils"
PKG_SECTION="virtual"
PKG_LONGDESC="Matapackage to install all alsa components."
