PKG_NAME="autotools"
PKG_VERSION=""
PKG_LICENSE="GPL"
PKG_SITE="http://www.openelec.tv"
PKG_URL=""
PKG_DEPENDS_HOST="ccache:host autoconf:host automake:host intltool:host libtool:host autoconf-archive:host"
PKG_SECTION="virtual"
PKG_LONGDESC="autotools: Metapackage"
