PKG_NAME="linux-firmware"
PKG_VERSION=""
PKG_URL=""
PKG_DEPENDS_TARGET="toolchain $FIRMWARE"
PKG_SECTION="virtual"
PKG_DESCRIPTION="linux-firmware is a meta-package to install various free firmware drivers"
