#!/bin/sh

message="$message\n There is no working 'apt-get'."
message="$message\n "
message="$message\n 'apt-get' is a command to install, update and remove software which"
message="$message\n is stored in a non local repo. 'apt-get' does nothing then connecting to such"
message="$message\n repo, downloads the software, unpacks the software, updates a big"
message="$message\n local database with all filepaths and other informations about the"
message="$message\n installed software or removes or updates installed Software."
message="$message\n "
message="$message\n With Clue it is not possible to change the system for security and"
message="$message\n stability reasons so even 'apt-get' would not be able to do this."
message="$message\n We also dont have and want to maintain such a repo for various other"
message="$message\n great reasons."
message="$message\n "

echo -e $message
exit 1
