#!/bin/sh

message="$message\n There is no working 'sudo'."
message="$message\n "
message="$message\n On debian/ubuntu/all general purpose linux distributions 'sudo'"
message="$message\n allows a permitted user to execute a command as the superuser"
message="$message\n or another user, as specified by the security policy"
message="$message\n "
message="$message\n With Clue you have root access by default, so you don't need 'sudo'"
message="$message\n "

echo -e $message

exit 1
