#!/bin/sh

# load release information
. /etc/os-release

wait4boot() {
	local message=$1
	local spinner="|/-\\|/-\\"
	local count=0
	local limit=120

	echo -en "${message} "
	while $(sleep 1); do
		if systemctl is-system-running | grep -qE "running|degraded" ; then
			echo -e "\bdone"
			break
		else
			echo -en "\b${spinner:$count:1}"
			count=$(((count + 1) % 8))
		fi

		limit=$((limit - 1))
		if [ $limit -le 0 ]; then
			echo -e "\bskip"
			break
		fi
	done
}

wait4kodi() {
	local message=$1
	local spinner="|/-\\|/-\\"
	local count=0
	local limit=60

	echo -en "${message} "
	while $(sleep 1); do
		if [ $(systemctl is-active "kodi") == "active" ]; then
			echo -e "\bdone"
			break
		else
			echo -en "\b${spinner:$count:1}"
			count=$(((count + 1) % 8))
		fi

		limit=$((limit - 1))
		if [ $limit -le 0 ]; then
			echo -e "\bskip"
			break
		fi
	done
}

isnormalrun() {
	target=$(systemctl get-default)
	boot=0

	for arg in $(cat /proc/cmdline); do
		if [ "$arg" = "debugging" -o "$arg" = "progress" -o "$arg" = "installer" ]; then
			boot=1
			break
		fi
	done

	[ $boot -ne 0 -o "$target" != "kodi.target" ] && return 1 || return 0
}

if isnormalrun ; then
	echo ""
	echo "Welcome to ${PRETTY_NAME}!"
	echo ""
	echo "    starting services...    "
	#wait4boot "    starting core services...    "
	#wait4kodi "    starting kodi services...    "
fi